# Generated by Django 3.0.8 on 2020-08-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhistory',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_auction_history', to='auctions.Item'),
        ),
    ]
